{% set name = "youtokentome" %}
{% set version = "1.0.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/youtokentome-{{ version }}.tar.gz
  sha256: 2e72fc110b804c7d63a4a5b04335397c48d9d66773233455d7e571561a6e448f

build:
  number: 5
  entry_points:
    - yttm = youtokentome.yttm_cli:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
  host:
    - cython
    - pip
    - python
  run:
    - click >=7.0
    - python

test:
  imports:
    - youtokentome
  commands:
    - pip check
    - yttm --help
  requires:
    - pip

about:
  home: https://github.com/vkcom/youtokentome
  summary: Unsupervised text tokenizer focused on computational efficiency
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - tyrius02
